# Be careful with indentation, this is a YAML file.
# MPRF configuration file.

# Production environment hide errors.
Production: false

# If the framework is installed in subdirectory on the server,
# set it as basepath. Include the first slash and exclude
# the last slash.
#
# E.g. '/api'
Basepath: /apiex

# If the servers is using any URL renaming module for hide index.php in URL,
# set this to true, if not, set it to false. If this option is not setted correctly,
# MPRF may work bad.
HiddenIndex: false

# API's version.
Version: r1

# API's author.
Author: MontyCLT

# API's name.
Name: HelloWord

# You can set different database credentials if you project need to
# connect with more than one database identified by name.
#
# The framework use Eloquent as ORM, this setting must be valid for an
# Capsule Manager.
#
# There are an examples of connection info, replace it for you database.
DatabaseCredentials:
  - name:      example1
    driver:    mysql
    host:      hostname1
    username:  username1
    password:  password1
    database:  database1
    charset:   utf8
    collation: utf8_unicode_ci
    prefix:

  - name:     test
    driver:   mysql
    host:     localhost
    username: root
    password: #Password can be empty
    database: test
    charset:   utf8
    collation: utf8_unicode_ci
    prefix: